unfoldingWord/tc-ui-toolkit

README.md
src/CheckInfoCard/__snapshots__/CheckInfoCard.test.js.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/4)

updated file structure in README.md

---

package-lock.json
package.json
src/CheckInfoCard/__snapshots__/CheckInfoCard.test.js.snap
tc-ui-toolkit-test/public/index.html
tc-ui-toolkit-test/src/App.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/5)

Added react-bootstrap support

---

package.json
src/VerseCheck/VerseCheck.styles.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/19)

Feature jay verse check card height

---

build/index.js
package.json
src/GroupMenu/Group/index.js
src/GroupMenu/GroupItems/index.js
src/GroupMenu/GroupMenu.js
src/GroupMenu/Groups/index.js
src/GroupMenu/helpers/index.js

This PR removes the logic that was done on the group menu to know if a verse is finished or not and it has been moved to the tW tool using the new api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/20)

Decoupled Alignment Data From ui kit

---

src/ScripturePane/ScripturePane.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/21)

Made necessary changes to make scripture pane use bible data from props

---

build/index.js
package.json
src/GroupMenu/Group/index.js
src/GroupMenu/GroupItem/index.js
src/GroupMenu/GroupItems/index.js
src/GroupMenu/GroupMenu.js
src/GroupMenu/helpers/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/23)

Group Menu Auto Scroll Fix

---

build/index.js
package.json
src/GroupMenu/Group/index.js
src/GroupMenu/GroupMenu.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/24)

Fix Item To Scroll To

---

build/index.js
package.json
src/GroupMenu/Group/index.js
src/GroupMenu/helpers/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/25)

Small Fixes For Group Menu Auto Scrolling

---

build/index.js
package.json
src/ScripturePane/ScripturePane.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/28)

Scripture Pane Locale

---

package-lock.json
package.json
tc-ui-toolkit-test/package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/29)

Fix For Dependencies

---

build/index.js
src/Bookmark/Bookmark.js
src/Bookmark/__snapshots__/Bookmark.test.js.snap
src/VerseCheck/ActionsArea/ActionsArea.styles.css
src/VerseCheck/ActionsArea/index.js
src/VerseCheck/VerseCheck.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/33)

Bookmark Switch Wrong Alignment

---

build/index.js
package-lock.json
src/GroupMenu/Group/index.js
src/GroupMenu/GroupMenu.js
tc-ui-toolkit-test/package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/34)

Menu Progress Bar Wrong Color

---

src/GroupMenu/GroupItem/index.js
src/ScripturePane/Pane/index.js
src/ScripturePane/ScripturePane.js
src/ScripturePane/Verse/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/37)

Fixed console log warnings for scripture pane and Group menu

---

build/index.js
package-lock.json
package.json
src/VerseCheck/MyLanguageModal/MyLanguageModal.styles.css
src/VerseCheck/MyLanguageModal/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/38)

Verse Check Pane Title Fix

---

build/index.js
package.json
src/GroupMenu/FilterBadge/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/39)

Removed 0 From Filter Menu When No Filters Selected

---

build/index.js
package-lock.json
package.json
src/VerseCheck/ActionsArea/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/43)

Cancel Button Enabled After Selection

---

build/index.js
package-lock.json
package.json
src/ScripturePane/helpers/__test__/fixtures/bibles.json
src/ScripturePane/helpers/__test__/fixtures/parsedBibles.json
src/ScripturePane/helpers/highlightHelpers.js
src/ScripturePane/helpers/verseHelpers.js
src/VerseCheck/__tests__/fixtures/project/loadedProjectShortened.json

- Updated English UDT references to UST.
- No longer using bible Ids in the code to determine to parse data to show the highlighted word.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/47)

Updated English UDT references to UST 

---

.npmignore
build/index.js
package-lock.json
package.json
src/ScripturePane/AddPaneModal/index.js
src/ScripturePane/ScripturePane.js

- In ScripturePane, added call to makeSureBiblesLoadedForTool() when resource is added.
- changed AddPaneModal to get selectable resource list from getAvailableScripturePaneSelections().
- make sure unit tests are passing on Travis (below)
- main testing will be done in the app
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/57)

feature 5030/Support Minimal loaded languages

---

.babelrc
package-lock.json
package.json
src/VerseCheck/utils/selectionHelpers.js

* Fixes some improperly called functions
* Fixes some babel dependencies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/60)

Fixes some function references and dependencies

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/64)

Fix For React Dependencies

---

package-lock.json
package.json
src/Bookmark/__snapshots__/Bookmark.test.js.snap
src/ScripturePane/helpers/verseHelpers.js
src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
tc-ui-toolkit-test/src/assets/scripturePaneProps.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/67)

merge release-v1.0.2 w/ master

---

package-lock.json
package.json
src/ScripturePane/helpers/__test__/stringHelpers.test.js
src/ScripturePane/helpers/stringHelpers.js
tc-ui-toolkit-test/src/assets/scripturePaneProps.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/68)

Fixed QA fail issues for missing text in the scripture pane

---

src/VerseCheck/DefaultArea/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/73)

Fixed bug w/ DefaultArea verse text

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/80)

Merging release into develop

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/81)

made a hard bump to 0.11 to ensure to tag the correct release

---

package.json
src/GroupMenu/GroupMenu.styles.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/85)

Release v1.0.2

---

package-lock.json
package.json
src/ScripturePane/helpers/__test__/__snapshots__/verseHelpers.test.js.snap
src/ScripturePane/helpers/__test__/fixtures/heb-12-27.grc.json
src/ScripturePane/helpers/__test__/fixtures/mat-4-6.json
src/ScripturePane/helpers/__test__/stringHelpers.test.js
src/ScripturePane/helpers/__test__/verseHelpers.test.js
src/ScripturePane/helpers/highlightHelpers.js
src/ScripturePane/helpers/stringHelpers.js
src/ScripturePane/helpers/verseHelpers.js

- fixes for spacing and added left double/single quotes support.
- unit tests should pass on Travis
- test with instructions in https://github.com/unfoldingWord-dev/translationCore/pull/5307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/77)

bugfix 5063/Fixes for quote spacing on ScripturePane

---

package-lock.json
package.json
src/ScripturePane/helpers/verseHelpers.js
src/WordLexiconDetails/WordLexiconDetails.js
src/WordLexiconDetails/WordLexiconDetails.test.js
src/WordLexiconDetails/__snapshots__/WordLexiconDetails.test.js.snap

For https://github.com/unfoldingword-dev/translationCore/issues/3087
Depends on https://github.com/translationCoreApps/word-aligner/pull/10/ and for word-aligner 0.2.4 to be published and then this package to update its version. SO DO NOT REVIEW/MERGE yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/89)

Feature - #3087 - Morphology to be a human readable string

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/90)

Updates tc-ui-toolkit version to 0.11.5

---

package-lock.json
package.json
src/WordLexiconDetails/__snapshots__/WordLexiconDetails.test.js.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/92)

Updates word-aligner to 0.2.5

---

package-lock.json
package.json
src/GroupMenu/Group/index.js
src/GroupMenu/helpers/index.js

fixes remaining issue in 5140:
- on redraw scrolls selected item to top of screen.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/94)

Feature 5140/fix auto scrolling near bottom

---

package-lock.json
package.json

updates to use the latest usfm-js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/95)

Bugfix mcleanb 5397/update dependencies

---

package-lock.json
package.json
src/ScripturePane/ScripturePane.js
src/ScripturePane/Verse/index.js
src/ScripturePane/helpers/verseHelpers.js

- added Hebrew (uhb) recognition as OL
- fixed verse reference direction for RTL languages.
- unit tests should pass
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/99)

Feature 1717/Add Old Hebrew support

---

package.json

Added script  to add tag each time tc-ui-toolkit is published
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/102)

Feature bspidel 5300

---

package.json
src/ScripturePane/Pane/index.js
src/ScripturePane/helpers/utils.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/105)

Added Localized Scripture Pane Description

---

package-lock.json
package.json
src/ScripturePane/helpers/__test__/lexiconHelpers.test.js
src/WordLexiconDetails/WordLexiconDetails.js
src/WordLexiconDetails/WordLexiconDetails.test.js
src/WordLexiconDetails/__snapshots__/WordLexiconDetails.test.js.snap

- refactored for testing.  improved handling for missing lemma and strongs.
- should pass unit tests on Travis
- can test with https://github.com/unfoldingWord-dev/translationCore/pull/5472
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/108)

Feature 5134

---

package-lock.json
package.json
src/Bookmark/__snapshots__/Bookmark.test.js.snap
src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap

- updated usfm-js and word-aligner
- see https://github.com/translationCoreApps/usfm-js/pull/68 for issues fixed.
- make sure unit tests pass.
- test using https://github.com/unfoldingWord-dev/translationCore/pull/5627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/137)

Bugfix 5388/Fix edge cases for USFM parsing

---

package-lock.json
package.json

- updated string-punctuation-tokenizer.
- unit tests should pass on Travis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/155)

Bugfix 5675

---

package-lock.json
package.json

- bumped version and updated dependencies
- test with https://github.com/unfoldingWord-dev/translationCore/pull/5811 and make sure UI in tools works fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/181)

Feature 5799/Tweaks for Whitespace support in USFM

---

package-lock.json
package.json
src/ScripturePane/ScripturePane.js
src/ScripturePane/helpers/verseHelpers.js

- In Scripture Pane when language is `hbo` then font size for verse is set to 200%
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/184)

Bugfix 5789/Increase font size for Hebrew in Scripture Pane

---

package-lock.json
package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/185)

updated usfm-js dependency

---

README.md
package-lock.json
package.json
src/GroupedMenu/FilteredMenu/MenuFilter.js
src/GroupedMenu/FilteredMenu/index.js
tc-ui-toolkit-test/src/App.js

- fixes for badge ordering and alignment
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/189)

Bugfix 5710/Fix Group Menu

---

package-lock.json
package.json
src/GroupedMenu/Menu/index.js

- fixes auto scrolling bug in tW that clicking on save or save & continue would not autoscroll current item into view (issue 8 on https://github.com/unfoldingword-dev/translationcore/issues/5710)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/191)

Bugfix 5710/Fix Autoscroll on save

---

package-lock.json
package.json

- updated to latest word-aligner and usfm-js with UGNT footnotes fix
- Travis should succeed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/196)

Bugfix 5964/Fix UGNT footnotes 

---

package-lock.json
package.json
src/ScripturePane/helpers/__test__/__snapshots__/verseHelpers.test.js.snap
src/ScripturePane/helpers/__test__/fixtures/luke-22-30.ult.json
src/ScripturePane/helpers/__test__/verseHelpers.test.js
src/ScripturePane/helpers/highlightHelpers.js

- add support of array of quoted words in tW.
- Travis should succeed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/199)

Bugfix 5970/fix rendering of multiple greek words in tW

---

package-lock.json
package.json
src/GroupedMenu/Menu/MenuGroup.js
src/GroupedMenu/Menu/MenuItem.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/202)

Removed Hover Effects From Side Bar

---

package-lock.json
package.json
src/ScripturePane/helpers/highlightHelpers.js
src/ScripturePane/helpers/verseHelpers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/203)

Added fix for context ids with empty occurrence numbers

---

package-lock.json
package.json
src/ScripturePane/helpers/highlightHelpers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/205)

Added changes to expand support for tN Greek snippets/quotes highlighting 

---

src/GroupMenu/GroupMenu.styles.css
src/GroupedMenu/Menu/MenuGroup.js
src/GroupedMenu/Menu/MenuItem.js
src/VerseCheck/ActionsArea/ActionsArea.styles.css
src/VerseCheck/ActionsArea/index.js
src/VerseCheck/VerseCheck.js
src/VerseCheck/__tests__/ViewCheck.test.js
src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
tc-ui-toolkit-test/src/App.js
tc-ui-toolkit-test/src/assets/groupedMenuProps.js
tc-ui-toolkit-test/src/assets/verseCheckProps.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/206)

UI changes for Translation Correct, Nothing to Select

---

package-lock.json
package.json
src/GroupedMenu/utils.js
src/ScripturePane/ExpandedScripturePaneModal/ChapterView/VerseRow/index.js
src/VerseCheck/ActionsArea/index.js
src/VerseCheck/CheckArea/index.js
src/VerseCheck/IconIndicators/index.js
src/VerseCheck/InstructionsArea/InstructionsArea.styles.css
src/VerseCheck/InstructionsArea/index.js
src/VerseCheck/InstructionsAreaTextSelection/index.js
src/VerseCheck/RenderSelectionTextComponent/index.js
src/VerseCheck/SaveArea/index.js
src/VerseCheck/VerseCheck.js
src/VerseCheck/__tests__/ViewCheck.test.js
src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
tc-ui-toolkit-test/src/App.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/207)

Fixes for nothingToSelect implementation 

---

package-lock.json
package.json
src/TranslationHelps/THelpsMarkDown/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/209)

added styling fix for tHelps

---

package-lock.json
package.json
src/VerseCheck/helpers/__tests__/checkAreaHelpers.test.js
src/VerseCheck/helpers/checkAreaHelpers.js
src/index.js

fixed getAlignedText to get correct instance and to be exported.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/210)

Bugfix 6143/Fix occurrence selected in 

---

package-lock.json
package.json
src/ScripturePane/ScripturePane.js
src/ScripturePane/helpers/verseHelpers.js
src/WordLexiconDetails/WordLexiconDetails.js
src/WordLexiconDetails/__snapshots__/WordLexiconDetails.test.js.snap

tweak Hebrew size and popup layout for new font
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/211)

Feature 6089/tweak Hebrew size for new font

---

package-lock.json
package.json
src/TranslationHelps/ExpandedHelpsModal/index.js
src/TranslationHelps/THelpsMarkDown/index.js
tc-ui-toolkit-test/src/App.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/213)
To test this PR run the `test` ui tookkit app and open the tHelps side panel. Ensure that the numbers say `1, 2, 3` and not `1, 1, 1`

New THelps Markdown Parser

---

src/ScripturePane/helpers/htmlElementsHelpers.js
src/ScripturePane/helpers/verseHelpers.js
src/WordLexiconDetails/WordLexiconDetails.js
src/WordLexiconDetails/WordLexiconDetails.test.js
src/WordLexiconDetails/__snapshots__/WordLexiconDetails.test.js.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/214)

Feature 6089/enlarge Hebrew/Greek fonts on lexicon popups

---

package-lock.json
package.json

- bumped version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/215)

Feature 6089/enlarge Hebrew/Greek fonts on lexicon 

---

package-lock.json
package.json
src/Bookmark/Bookmark.js
src/Bookmark/__snapshots__/Bookmark.test.js.snap
src/GroupedMenu/Menu/ProgressIcon.js
src/VerseCheck/EditVerseArea/index.js
src/VerseCheck/VerseCheck.js
src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
src/VerseEditor/ReasonCheckbox.js
src/VerseEditor/VerseEditorStepper.js
tc-ui-toolkit-test/src/App.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/218)

Added correct color scheme

---

package-lock.json
package.json
src/ScripturePane/ScripturePane.js

Just needs a review for passing an (optional) function handleModalOpen to ScripturePane to send if a modal was open (true) or closed (false).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/219)

Fixes #5930 - clear activated words in word bank

---

package-lock.json
package.json
src/ScripturePane/ScripturePane.js

Quick change for how the handleModalOpen() function is accessed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/220)

Fix - #5930 - Change to how function is accessed

---

package-lock.json
package.json
src/VerseCheck/CheckArea/index.js
src/VerseCheck/RenderSelectionTextComponent/index.js
src/VerseCheck/SelectionArea/index.js
src/VerseCheck/VerseCheck.js
tc-ui-toolkit-test/src/App.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/221)

Feature 6133/pass maximum number of selections as a property

---

package-lock.json
package.json
src/VerseCheck/ActionsArea/index.js
src/VerseCheck/EditVerseArea/index.js
src/VerseCheck/SelectionArea/index.js
src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/222)

Fixed Verse Check Pane Text and Buttons Overflow

---

package-lock.json
package.json
src/ScripturePane/helpers/__test__/__snapshots__/verseHelpers.test.js.snap
src/ScripturePane/helpers/__test__/verseHelpers.test.js
src/ScripturePane/helpers/verseHelpers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/223)

Bugfix 6193/Fix to disable clickable lexicons in bibles other than ugnt and uhb

---

package-lock.json
package.json
src/VerseCheck/CheckArea/index.js
src/VerseCheck/VerseCheck.js
src/VerseCheck/__tests__/fixtures/project/loadedProjectShortened.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/225)

Renamed variables

---

package-lock.json
package.json
src/CheckInfoCard/PhraseWithToolTip.js

Our regex to find Bible references with Markdown link syntax assumed Latin characters. This fixes that to match Hindi Bible references.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/227)

Fixes bible regex to match Hindi(non-latin character languages) bible references

---

package-lock.json
package.json
src/GroupedMenu/Menu/MenuItem.js
src/GroupedMenu/Menu/index.js
src/GroupedMenu/utils.js

- add spinner to group menu navigation.
- performance tweaks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/229)

Feature 3579/add spinner to group menu navigation

---

package-lock.json
package.json
src/GroupedMenu/Menu/MenuItem.js
src/GroupedMenu/Menu/index.js

removed spinner on cursor for group menu navigation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/230)

feature 3579/removed spinner on cursor for group menu navigation

---

package.json
src/GroupedMenu/FilteredMenu/index.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/235)

Grouped Menu React Memo

---

package-lock.json
package.json
src/VerseCheck/helpers/__tests__/selectionHelpers.test.js
src/VerseCheck/helpers/selectionHelpers.js

- fix to reject selected space(s).
- added trimming of white space on selections
- change to merge adjoining selections as per user feedback.
- test with build attached below
- in tN or tW:
- make sure that any attempts to select space(s) only are ignored.
- make sure on drag selections that leading and trailing spaces are trimmed.
- make sure on double-click selections that the selected word is attached to any adjacent selections if just separated by space(s).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/237)

Bugfix 6491/fixes for selections

---

package-lock.json
package.json
src/ScripturePane/helpers/__test__/__snapshots__/verseHelpers.test.js.snap
src/ScripturePane/helpers/__test__/fixtures/jhn-6-21-en-t4t.json
src/ScripturePane/helpers/__test__/verseHelpers.test.js
src/ScripturePane/helpers/usfmHelpers.js
src/ScripturePane/helpers/verseHelpers.js
src/VerseCheck/helpers/__tests__/selectionHelpers.test.js
src/VerseCheck/helpers/selectionHelpers.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/240)

merge latest Release v2.1.0

---

package.json
src/CommentsDialog/BaseDialog.js
src/CommentsDialog/CommentsDialog.js
src/CommentsDialog/__tests__/CommentsDialog.test.js
src/CommentsDialog/__tests__/__snapshots__/CommentsDialog.test.js.snap
src/CommentsDialog/index.js
src/index.js

- added CommentsDialog and made draggable
- can test with build on https://github.com/unfoldingWord/translationCore/pull/6673
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/251)

Feature 5407/added CommentsDialog.

---

package-lock.json
package.json
src/ScripturePane/ScripturePane.styles.css
src/VerseCheck/VerseCheck.styles.css

- fix scripture pane scroll behavior so it won't shrink vertically
- fix verse check area so it will expand vertically to fill space
-  checkout tCore branch `bugfix-mcleanb-6731.2`.  Do `rm -rf ./node_modules && npm ci && npm run load-apps && npm start`
- open wa, tw and tn tools to make sure that layout is not broken.  See https://github.com/unfoldingword/translationcore/issues/6731
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/253)

Bugfix 6731/Fix tool layout

---

package-lock.json
package.json
src/ScripturePane/helpers/verseHelpers.js
webpack.config.js

- update string-punctuation-tokenizer
- adjust for string-punctuation-tokenizer api changes
- made string-punctuation-tokenizer and word-aligner peer/external dependencies
- can test with tC branch `bugfix-mcleanb-6831`
- all tN checks in Ruth should open without error.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/255)

Bugfix 6831/Fixes for tokenizing Hebrew words

---

package-lock.json
package.json
src/ScripturePane/ScripturePane.styles.css
src/VerseCheck/VerseCheck.styles.css

- merged the sandbox-electronite into develop
- test with tCore branch `merge-sandbox` (https://github.com/unfoldingWord/translationCore/pull/6844)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/256)

Merge sandbox

---

package-lock.json
package.json
src/ScripturePane/helpers/verseHelpers.js
webpack.config.js

- updated string-punctuation-tokenizer
- make string-punctuation-tokenizer and word-aligner external dependencies
- can test with tCore branch `merge-hotfix-2.1.2`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/259)

Merge hotfix 2.1.2

---

.babelrc
package-lock.json
package.json
src/GroupedMenu/FilteredMenu/index.js
src/GroupedMenu/Menu/MenuItem.js
src/GroupedMenu/Menu/index.js
src/ScripturePane/ExpandedScripturePaneModal/ChapterView/VerseRow/index.js
src/ScripturePane/ExpandedScripturePaneModal/ChapterView/index.js
src/ScripturePane/ExpandedScripturePaneModal/index.js
src/ScripturePane/Pane/index.js
src/ScripturePane/ScripturePane.js
src/ScripturePane/Verse/index.js
src/ScripturePane/helpers/verseHelpers.js
src/VerseCheck/CheckArea/index.js
src/VerseCheck/DefaultArea/index.js
src/VerseCheck/EditVerseArea/index.js
src/VerseCheck/InstructionsArea/index.js
src/VerseCheck/InstructionsAreaTextSelection/index.js
src/VerseCheck/MyLanguageModal/index.js
src/VerseCheck/MyTargetVerse/index.js
src/VerseCheck/RenderSelectionTextComponent/index.js
src/VerseCheck/SelectionArea/index.js
src/VerseCheck/VerseCheck.js
src/VerseCheck/__tests__/ViewCheck.test.js
src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
src/VerseEditor/EditScreen.js
src/VerseEditor/VerseEditor.js
src/common/fontUtils.js

Please use steps in https://github.com/unfoldingWord/translationCore/pull/6949 for testing
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/263)

Added target language font selection support 

---

.gitignore
package-lock.json
package.json
src/ScripturePane/ExpandedScripturePaneModal/ChapterView/index.js
src/ScripturePane/Pane/index.js
src/ScripturePane/ScripturePane.js
src/ScripturePane/Verse/index.js
src/ScripturePane/helpers/utils.js
src/VerseCheck/VerseCheck.js
src/VerseEditor/EditScreen.js
src/VerseEditor/VerseEditor.js
src/VerseEditor/__tests__/__snapshots__/VerseEdit.test.js.snap
src/index.js

- fix RTL support in sub-panes of the SP - including change to <verse>:<chapter>, remove glyph on right
- can test with github build attached to https://github.com/unfoldingWord/translationCore/pull/6948 and this project: 
[08-RUT-AR.usfm.zip](https://github.com/unfoldingWord/tc-ui-toolkit/files/4688438/08-RUT-AR.usfm.zip)
- all issues should be working in https://github.com/unfoldingWord/translationCore/issues/5194 such as: 
- for SP and verse editor in WA: 
- and for enhanced Scripture Pane:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/262)

Feature 5194/Fix for RTL in SP

---

package-lock.json
package.json
src/VerseCheck/InstructionsAreaTextSelection/index.js

Follow test instructions in https://github.com/unfoldingWord/translationCore/pull/6949
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/264)

Fixed bug where complex script font was not being used properly

---

package-lock.json
package.json
src/GroupedMenu/Menu/MenuItem.js
src/GroupedMenu/Menu/index.js
src/GroupedMenu/__tests__/utils.test.js
src/GroupedMenu/utils.js

- RTL fix for group Menus
- test with actions build attached to https://github.com/unfoldingWord/translationCore/pull/6951
- use this project for testing: 
[ar_zzz_phm_book.zip](https://github.com/unfoldingWord/tc-ui-toolkit/files/4711752/ar_zzz_phm_book.zip)
- Should see these arrangements in the group menu in the various tools:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/265)

Feature 5195/RTL fix for group Menus

---

package-lock.json
package.json
src/ScripturePane/AddPaneModal/index.js
src/ScripturePane/ExpandedScripturePaneModal/index.js
src/ScripturePane/ScripturePane.js

Use instructions in https://github.com/unfoldingWord/translationCore/pull/6958 for testing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/267)

Improved scripture pane performance by memoizing props

---

package-lock.json
package.json
src/ScripturePane/ExpandedScripturePaneModal/ChapterView/index.js
src/ScripturePane/ScripturePane.js
src/VerseCheck/VerseCheck.js
src/VerseCheck/__tests__/ViewCheck.test.js
src/common/fontUtils.js

Follow test instructions in https://github.com/unfoldingWord/translationCore/pull/6962#issue-427394776
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/268)

Renamed "language font" to "project font"

---

package-lock.json
package.json
src/ScripturePane/Pane/index.js
src/ScripturePane/ScripturePane.js
src/VerseCheck/DefaultArea/index.js
src/VerseCheck/InstructionsArea/index.js
src/VerseCheck/MyLanguageModal/index.js
src/VerseCheck/MyTargetVerse/index.js
src/VerseCheck/RenderSelectionTextComponent/index.js
src/VerseCheck/SelectionArea/index.js
src/VerseEditor/EditScreen.js
src/VerseEditor/VerseEditor.js
src/VerseEditor/__tests__/__snapshots__/VerseEdit.test.js.snap

- Follow test instructions in https://github.com/unfoldingWord/translationCore/pull/6976#issue-428460505
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/270)

Complex script font fixes

---

package-lock.json
package.json
src/ScripturePane/Pane/index.js

- fix SP RTL
- test with tC branch bugfix-mcleanb-5194
- Should fix QA fail in issue - RTL in SP title
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/271)

Bugfix 5194/Fix RTL on SP title

---

package-lock.json
package.json
src/CommentsDialog/BaseDialog.js
src/CommentsDialog/CommentsDialog.js
src/CommentsDialog/__tests__/__snapshots__/CommentsDialog.test.js.snap
src/DropdownMenu/DropdownMenu.js
src/ScripturePane/Pane/index.js
src/ScripturePane/ThreeDotMenu/index.js
src/ScripturePane/Verse/index.js
src/ThreeDotIcon/ThreeDotIcon.js
src/VerseCheck/DefaultArea/index.js
src/VerseCheck/SelectionArea/index.js
src/VerseEditor/VerseEditor.js
src/VerseEditor/__tests__/__snapshots__/VerseEdit.test.js.snap

Follow test instructions in https://github.com/unfoldingWord/translationCore/pull/7020
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/277)

Addressed QA fails for Complex script fonts

---

package-lock.json
package.json
src/ScripturePane/Pane/Pane.styles.css
src/ScripturePane/Pane/index.js
src/ScripturePane/Panes/index.js
src/ScripturePane/Verse/Verse.styles.css

- Please use instructions in https://github.com/unfoldingWord/translationCore/pull/7026 to test
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/278)

Addressed QA fail issues with target language text resizing

---

package-lock.json
package.json
src/DropdownMenu/DropdownMenu.js

- add absolute positioning support to DropdownMenu
- test with tC branch `bugfix-mcleanb-7028`
- in wA, when changing font size on word bank, should not see font resize slider move.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/288)

Bugfix 7028/Make Word Bank font sizer stationary

---

package-lock.json
package.json
src/FontSelectionMenu/FontSelectionMenu.js
src/ScripturePane/Pane/index.js
src/ScripturePane/ThreeDotMenu/index.js

Use test instructions in https://github.com/unfoldingWord/translationCore/pull/7071
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/291)

Fixed text for Hebrew font selection menu item

---

package-lock.json
package.json
src/VerseEditor/EditScreen.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/296)

Merge Release v3.0.0 into develop
