unfoldingWord/tc-ui-toolkit

build/index.js, package.json, src/VerseCheck/InstructionsArea/index.js, src/VerseCheck/__tests__/ViewCheck.test.js, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
- fixes issue in tW that if the initial verse was invalidated, it would start up with select verse
- Local testing setup: 
`git fetch`
`git checkout develop`
`git pull`
`npm run update-apps`
`npm i`
`rm -rf node_modules/tc-ui-toolkit`
`npm i translationCoreApps/tc-ui-toolkit#feature-mcleanb-3086/ShowInvalidatedSelection.5`
`npm start`
- Test steps:
- open tw tool.  
- Under blameless, for vs 1:6 select "without blame" 
- edit 1:6 to remove space to make selection "withoutblame".  
- verify invalidated icon on group menu and on verse check bar and invalidated message on instructions.  
- Exit tw tool
- open tw tool again and verify invalidated icon on group menu and on verse check bar and invalidated message on instructions.  
This change is [<img …
=> Feature 3086/show invalidated selection - current verse Fix

build/index.js, package-lock.json, package.json, src/ScripturePane/helpers/verseHelpers.js, tc-ui-toolkit-test/src/assets/scripturePaneProps.js
- load the tc-ui-toolkit-test and it should only render hello in the target language pane
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/48)
=> Now removing \pi USFM marker in the the scripture pane

package.json, src/GroupMenu/GroupItem/index.js, src/GroupMenu/GroupMenu.styles.css
Related to https://github.com/unfoldingWord-dev/translationCore/issues/5097
I forgot to change the book title and style the tooltip properly.
*  book title is abbreviated when a selection is made
* tooltip is now gray with black text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/72)
=> Finishes styles and formatting to truncated text

package.json, src/GroupMenu/Group/index.js, src/GroupMenu/GroupMenu.styles.css
Related to https://github.com/unfoldingWord-dev/translationCore/issues/5140.
Also related to https://github.com/unfoldingWord-dev/translationCore/issues/5097 since the fix was super tiny.
- This updates the group menu to only scroll to the selected context when the tool starts and when a group is opened.
- Fixes the clickable area of a group so that groups can be opened by clicking anywhere on the header instead of just on the text.
- Corrects the background color of popups in the groups menu.
Here's an illustration of the improvement
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/75)
=> Fixes menu scroll

package-lock.json, package.json, src/ScripturePane/helpers/bibleHelpers.js, tc-ui-toolkit-test/src/assets/scripturePaneProps.js
- On tC `release-v1.0.2` run `npm i translationCoreApps/tc-ui-toolkit#bugfix-mannycolon-5266 `
- Open [es-419_reg_luk_book.zip](https://github.com/unfoldingWord-dev/translationCore/files/2490175/es-419_reg_luk_book.zip) w/ tW tool
- Go to Luke 1:2 on `word of God, words of God, word of Yahweh, word of the Lord, word of truth, scripture, scriptures` check
- The following warning should show
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/86)
=> Fixed missing text warning not displayed in scripture pane

package.json, src/GroupMenu/Group/index.js, src/GroupMenu/helpers/index.js
fixes remaining problems in 5140:
- fix view window calculations for if active item is on screen.
- change to scroll active item to top of view window if it is off screen.
- fixes to behavior of group menu clicks and expansion icon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/91)
=> Bugfix 5140/Fix auto scrolling & Group item expansion/collapse issues

package-lock.json, package.json, src/ScripturePane/helpers/lexiconHelpers.js, src/WordLexiconDetails/WordLexiconDetails.test.js
- lexiconHelpers - added support for ZERO_WIDTH_JOINER in splitting word.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/195)
=> Feature 5863/fix WordLexiconDetails when word has a ZERO_WIDTH_JOINER

package-lock.json, package.json, src/ScripturePane/helpers/highlightHelpers.js, src/ScripturePane/helpers/verseHelpers.js
- Fixed bug where the scripture pane wasn't highlighting punctuation between highlighted words
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/204)
=> Fixed bug where the scripture pane wasn't highlighting punctuation between highlighted words 

package-lock.json, package.json, src/ScripturePane/ExpandedScripturePaneModal/ChapterView/index.js, src/ScripturePane/ExpandedScripturePaneModal/index.js, src/VerseCheck/ActionsArea/ActionsArea.styles.css, src/VerseCheck/ActionsArea/index.js, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap, src/VerseEditor/BaseDialog.js, src/VerseEditor/VerseEditor.js
- Added info icon to "no selection needed" checkbox
- Made expanded scripture pane and verse editor dialogs draggable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/208)
=> Added info icon to "no selection needed" checkbox & made expanded scripture pane and verse editor dialogs draggable

package-lock.json, package.json, src/ScripturePane/ScripturePane.js
- override description of additional original language resources to show original language instead of gateway language.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/216)
=> Feature 6193/Support for more than one original language.

package-lock.json, package.json, src/TranslationHelps/TranslationHelps.js, src/VerseCheck/ActionsArea/index.js, src/VerseCheck/CheckArea/index.js, src/VerseCheck/CommentArea/index.js, src/VerseCheck/DefaultArea/index.js, src/VerseCheck/EditVerseArea/index.js, src/VerseCheck/IconIndicators/index.js, src/VerseCheck/InstructionsArea/index.js, src/VerseCheck/MyLanguageModal/index.js, src/VerseCheck/RenderSelectionTextComponent/index.js, src/VerseCheck/SaveArea/index.js, src/VerseCheck/SelectionArea/index.js, src/VerseCheck/VerseCheck.js, src/VerseCheck/VerseCheck.styles.css, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap, src/VerseCheck/__tests__/fixtures/project/loadedProjectShortened.json, tc-ui-toolkit-test/src/App.js, tc-ui-toolkit-test/src/assets/commentsReducer.js, tc-ui-toolkit-test/src/assets/loginReducer.js, tc-ui-toolkit-test/src/assets/remindersReducer.js, tc-ui-toolkit-test/src/assets/resourcesReducer.js, tc-ui-toolkit-test/src/assets/selectionsReducer.js, tc-ui-toolkit-test/src/assets/verseCheckProps.js
- In translationCore repo checkout to `feature-mannycolon-6443-6446` and run `npm i`
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/translationcoreapps/tc-ui-toolkit/234)
=> Refactored verseCheck to use explicit props instead of entire reducers

package-lock.json, package.json, src/ScripturePane/helpers/__test__/__snapshots__/verseHelpers.test.js.snap, src/ScripturePane/helpers/__test__/fixtures/jhn-6-21-en-t4t.json, src/ScripturePane/helpers/__test__/verseHelpers.test.js, src/ScripturePane/helpers/usfmHelpers.js, src/ScripturePane/helpers/verseHelpers.js, src/VerseCheck/helpers/selectionHelpers.js
- fix problem that spaces in html are not always shown by replacing leading and trailing spaces with no-break-space.
- fix problem with displaying in HTML: USFM that has an end marker.
- use test build attached below.
- update english resources to get the t4t bible.
- open a John project and launch WA tool
- navigate to John 6:4
- add the t4t (translation for translators) to the scripture pane and make sure the issue in https://github.com/unfoldingword/translationcore/issues/6008 is fixed.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/238)
=> Bugfix 6008/fix spacing problem in T4T

package-lock.json, package.json, src/ScripturePane/helpers/__test__/__snapshots__/verseHelpers.test.js.snap, src/ScripturePane/helpers/usfmHelpers.js, src/ScripturePane/helpers/verseHelpers.js
- removed non-break space which caused rendering problem.  Now using our standard space span.
- can use test build attached below.
- update english resources to get the t4t bible.
- open a John project and launch WA tool
- add the t4t (translation for translators) to the scripture pane
- navigate to John 6:21  and make sure the original issue in unfoldingWord/translationCore#6008 is fixed in t4t.
- navigate to John 18:38 and make sure `"How` is rendered correctly without a space after `"`
- navigate to John 19:14 and make sure it is rendered like screenshot in x2.1.0 (605b3a6) 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/241)
=> Bugfix 6008/Fix whitespace rendering

package-lock.json, package.json, src/ScripturePane/AddPaneModal/index.js
- On the dialog to add resources to the scripture pane, localize close and load buttons
- use test build attached below.
- for each tool: wa, tw, tn:
- launch tool
- make sure locale is set to English
- on Scripture pane click on add resources icon.
- from drop down, select a resource
- on dialog, should see valid text on Close and Load buttons
- click Close button
- set locale to language other than English
- on Scripture pane click on add resources icon.
- from drop down, select a resource
- on dialog, should see valid text on Close button (left).  Load button should say "missing translation key..." since we do not yet have translation for the button text.
- click Close button (left)
- change locale to English
This change is [<img src="https://reviewable.io/review_button.svg" …
=> Bugfix 5705/On the dialog to add resources to the scripture pane, localize close and load buttons

package-lock.json, package.json, src/VerseCheck/ActionsArea/index.js, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
- localize "No selection Needed" string
- fix helps string to use correct key.
- use test build below.  Make sure that "No selection Needed" checkbox is localized in tW and tN.  Should see localized strings for Spanish and Hindi.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/244)
=> Bugfix 6025/fix to localize "No selection Needed"

package-lock.json, package.json, src/VerseCheck/ActionsArea/index.js, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
- revert locale key change back to `nothing_to_select_description`  to Fix hover for "No selection Needed" checkbox
- use test build below.  Make sure that "No selection Needed" checkbox is localized in tW and tN.  Should see localized strings for the checkbox and hover in Spanish and Hindi.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/245)
=> Bugfix 6025/Fix hover for "No selection Needed" checkbox

package-lock.json, package.json, src/CheckInfoCard/PhraseWithToolTip.js, src/CheckInfoCard/__snapshots__/CheckInfoCard.test.js.snap
- added html support to PhraseWithTooltip
- can test with attached build.  Should support emphasis in tN.  
- open a titus project with GL set to EN and should not see the *** displayed checks (see https://github.com/unfoldingword/translationcore/issues/6600)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/247)
=> Feature 6600/Add Markdown support for occurrence notes in tN

package.json, src/CheckInfoCard/CheckInfoCard.js, src/CheckInfoCard/PhraseWithToolTip.js, src/CheckInfoCard/__snapshots__/CheckInfoCard.test.js.snap, webpack.config.js
This is related to https://github.com/unfoldingword/translationcore/issues/6351
* Displays clickable tA links.
* Clicks can be handled by adding an `onLinkClick` prop to `CheckInfoCard`
**Other changes**
* Added react-dom to webpack's `externals` so that it can function like a proper peer-dependency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/254)
=> Display tA links in the check info ("smurf") card

package.json, src/CheckInfoCard/PhraseWithToolTip.js
Related to https://github.com/unfoldingword/translationcore/issues/6858
* Adds null checking
* Adds support for rendering links when there is also a verse tooltip.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/260)
=> Fixes null bug in check info card.

package-lock.json, package.json, src/VerseCheck/InstructionsArea/index.js, src/VerseCheck/InstructionsAreaTextSelection/index.js
- fix parameter type children for QuotationMarks to be an array.
- test with tC branch bugfix-mcleanb-6733
- should not see any change in tC
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/272)
=> Bugfix 6733/Fix property errors

package-lock.json, package.json, src/ScripturePane/ScripturePane.js, src/ScripturePane/helpers/verseHelpers.js, src/WordLexiconDetails/WordLexiconDetails.js
- fix for Hebrew fonts being clipped and too bold
- test with tC build bugfix-mcleanb-6984
- in OT projects in wA  should not see the clipping of Hebrew in Alignment grid area and text should be less bold:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/275)
=> Bugfix 6984/Fix for Hebrew fonts being clipped and too bold

package-lock.json, package.json, src/GroupedMenu/Menu/MenuItem.js, src/VerseCheck/helpers/selectionHelpers.js
- added compensation for padding on tooltip calculations
- added separate padding amounts for ltr and rtl.
- added sanity check for selection to make sure array is not empty
- added delay before overflow calculations to so that rendering completes first
- in tn and tw group menu overflows should show like this in rtl languages.  And group menu entries should not have book name:
- and for ltr languages:
- in WA group menu should show like this without book name in rtl languages:
- and for ltr languages:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/279)
=> Bugfix 6988/Fix group menu tooltips overflow calculations

package-lock.json, package.json, src/VerseCheck/RenderSelectionTextComponent/index.js, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap, src/VerseCheck/helpers/selectionHelpers.js, src/VerseCheck/helpers/stringHelpers.js, src/VerseCheck/helpers/windowSelectionHelpers.js
- added detection of double-click from mouse events
- Fix for double-click near end of word in checking tools
- fixed typo `presceding` to `preceding`
- use build attached to: https://github.com/unfoldingWord/translationCore/pull/7039
- see issue https://github.com/unfoldingword/translationcore/issues/7024 - should be able to double-click near end of word and select it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/281)
=> Bugfix 7024/Fix double click near end of word in checking tools

package-lock.json, package.json, src/VerseCheck/DefaultArea/index.js, src/VerseCheck/SelectionArea/index.js
- fix verse title right padding when rtl to match text area in default and selection mode
- verse title right padding when rtl should match text area in default mode and selection mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/282)
=> Bugfix 7043/fix verse title right padding with RTL languages

package-lock.json, package.json, src/ScripturePane/ExpandedScripturePaneModal/ChapterView/index.js, src/VerseCheck/CheckArea/index.js, src/VerseCheck/EditVerseArea/index.js, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap, src/VerseEditor/EditScreen.js, src/VerseEditor/VerseEditor.js, src/VerseEditor/__tests__/__snapshots__/VerseEdit.test.js.snap
- added font size to verse edit dialog in verseCheck and in verseEditor (used by EnhancedScripturePane and called by wA)
- use build attached to https://github.com/unfoldingWord/translationCore/pull/7050
- in wA, text size in verse editor should match text size in alignment grid area:
- in enhanced scripture pane, text size  in verse editor should match text size in target language pane:
- in tW and tN, text size in verse editor should match text size in selection area:
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/283)
=> Feature 7038/Make verse edit fonts resizable

package-lock.json, package.json, src/VerseCheck/CheckArea/index.js, src/VerseCheck/InstructionsArea/index.js, src/VerseCheck/InstructionsAreaTextSelection/index.js
- Fix quotes for selections in instructions area of verse check
- use tC branch bugfix-mcleanb-7041 for testing
- this will fix the problem with quotes in the first example (ar_nav_oba_book 2.zip) in issue https://github.com/unfoldingword/translationcore/issues/7041
- note that the second issue is not fixable since they selected a character that is supposed to be joined to character before it.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/285)
=> Bugfix 7041/Fix quotes for selections in instructions area of verse check

package-lock.json, package.json, src/VerseCheck/EditVerseArea/index.js, src/VerseCheck/__tests__/__snapshots__/ViewCheck.test.js.snap
- for tN & tW, fixed font sizing in EditVerseArea for default font
- use tC branch `bugfix-mcleanb-7038` for testing
- in tN & tW: make sure target font is default. Click edit verse and text size should match size in selection/review area.  Drag font size slider up and down - should see font size in edit area changing with slider.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/286)
=> Bugfix 7038/Fix font resizing in tW & tN verse edit boxes for default font

package-lock.json, package.json, src/VerseEditor/EditScreen.js
- add direction to edit screen in scripture pane.
- test with build attached to https://github.com/unfoldingWord/translationCore/pull/7082
- open an arabic project in tN or tW.  Open expanded scripture pane.  Click to edit any verse that has punctuation at the end of verse, and should see punctuation in the verse editor in same order as shown in expanded scripture pane.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/unfoldingword/tc-ui-toolkit/295)
=> Bugfix 7081/Fix order of punctuation in SP edit boxes for RTL languages.
